[package]
name = "ritc"
authors = ["Harry Thomas @infosechoudini"]
description = "Rust Inline Toolchain - Raw system calls and networking"
keywords = ["net", "syscall", "system", "no_std"]
version = "0.1.0"
edition = "2021"
license="Apache-2.0"
readme = "README.md"
categories = ["network-programming", "no-std-library", "embedded-development", "operating-systems"]

[lib]
name = "ritc"
crate-type = ["rlib", "cdylib"]

[dependencies]
rustc-std-workspace-core = { version = "1.0.0", optional = true }

[features]
default = ["rustc-dep-of-std"]
std = []
align = []
rustc-dep-of-std = ['align', 'rustc-std-workspace-core']

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
libc = "0.2"

[[bench]]
name = "syscalls"
harness = false
